package:
  name: dmscore_r_env
  version: "1.0.0"

source:
  path: .

build:
  number: 0
  script: |
    mkdir -p $PREFIX/bin
    cp -r R_scripts/* $PREFIX/bin/
    chmod +x $PREFIX/bin/*

requirements:
  build:
    - r-base >=4.4
  run:
    - r-base >=4.4
    - r-dplyr ==1.1.4
    - r-ggplot2 ==3.5.1
    - r-scales ==1.3.0
    - r-zoo ==1.8.12
    - r-reshape2 ==1.4.4
    - r-tidyr ==1.3.1
    - r-tidyverse ==2.0.0
    - r-stringr ==1.5.1
    - bioconductor-biostrings

about:
  home: https://github.com/BenjaminWehnert1008/dmscore_R_env.git
  license: MIT
  summary: "Environment with R scripts and packages for R processes in dmscore pipeline"
